<a href="https://colab.research.google.com/github/cahyotriatmojo/DM_Processing/blob/main/Preprocessing4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset. iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Solo' 20.0 120.0]
 ['Tegal' 27.0 318.0]
 ['Solo' 30.0 90.0]
 ['Demak' 23.0 210.0]
 ['Solo' 40.0 nan]
 ['Tegal' 35.0 122.0]
 ['Teagl' nan 20.0]
 ['Demak' 48.0 790.0]
 ['Solo' 60.0 130.0]
 ['Demak' 37.0 70.0]]


[:, :-1] pilih semua baris dalam dataset, serta semua kolom
kecuali kolom terakhir(LABEL).

In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


[:, -1]  pilih semua baris, kolom terakhir.   PRINT DATA LABEL

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Solo' 20.0 120.0]
 ['Tegal' 27.0 318.0]
 ['Solo' 30.0 90.0]
 ['Demak' 23.0 210.0]
 ['Solo' 40.0 207.77777777777777]
 ['Tegal' 35.0 122.0]
 ['Teagl' 35.55555555555556 20.0]
 ['Demak' 48.0 790.0]
 ['Solo' 60.0 130.0]
 ['Demak' 37.0 70.0]]


Menambahkan library sklearn
• Class SimpleImputer() digunakan untuk mengganti nilai yang
kosong dengan mean kolom.
• missing_values : nilai data yang digunakan sebagai
penanda bahwa nilai aslinya tidak ada (missing); dalam hal
ini NaN (np.nan)
• strategy : dalam hal ini rata-rata kolom ('mean'), bisa juga
menggunakan 'median', 'most_frequent' (modus),
atau 'constant’.
• Selanjutnya obyek imputer harus di fit berdasarkan kolom yang
bersangkutan menggunakan metode fit()

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder (), [0])], remainder='passthrough')
x = np.array(ct. fit_transform(x))

matrik x sebelumnya pada Kota bertype string, jadi diubah ke (int atau float). 

In [8]:
print(x)

[[0.0 1.0 0.0 0.0 20.0 120.0]
 [0.0 0.0 0.0 1.0 27.0 318.0]
 [0.0 1.0 0.0 0.0 30.0 90.0]
 [1.0 0.0 0.0 0.0 23.0 210.0]
 [0.0 1.0 0.0 0.0 40.0 207.77777777777777]
 [0.0 0.0 0.0 1.0 35.0 122.0]
 [0.0 0.0 1.0 0.0 35.55555555555556 20.0]
 [1.0 0.0 0.0 0.0 48.0 790.0]
 [0.0 1.0 0.0 0.0 60.0 130.0]
 [1.0 0.0 0.0 0.0 37.0 70.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Matrik Y hanya akan diubah menjadi numerik(0, 1 , dan seterusnya) dengan LabelEncoder.


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_test)

[[0.0 1.0 0.0 0.0 30.0 90.0]
 [1.0 0.0 0.0 0.0 37.0 70.0]]


Test_size : Proporsi test set, dalam hal ini 0.2

In [13]:
print(y_test)

[0 1]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


Train_size : Proporsi train size. jika tidak di set, maka akan menyesuaikan dengan test size (dalam kasus ini 0.8). Berlaku kebalikannya.

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

StandarScaler menghilangkan mean (terpusat pada 0) dan menskalakan ke variansi (deviasi standar = 1).

In [16]:
print(x_test)

[[0.0 1.0 0.0 0.0 -0.48688971811658505 -0.6701264755622031]
 [1.0 0.0 0.0 0.0 0.07464899568377863 -0.7596424426131838]]


In [17]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.04122407224328042 -0.9834323602406356]
 [0.0 1.0 0.0 0.0 0.31530844445536305 -0.14297689181753873]
 [0.0 1.0 0.0 0.0 -1.289087880688533 -0.535852524985732]
 [1.0 0.0 0.0 0.0 -1.0484284319169488 -0.13303067325631862]
 [0.0 0.0 0.0 1.0 -0.7275491668881695 0.35035554881897735]
 [1.0 0.0 0.0 0.0 0.9570669745129216 2.462932371222123]
 [0.0 1.0 0.0 0.0 1.9197047695992593 -0.49109454146024156]
 [0.0 0.0 0.0 1.0 -0.08579063683061099 -0.5269009282806338]]
